apiVersion: v1
kind: Pod
metadata:
  name: gpu-operator-test-a10
spec:
  restartPolicy: OnFailure
  containers:
  - name: cuda-vector-add
    image: "nvidia/samples:vectoradd-cuda11.6.0"
    resources:
      limits:
         nvidia.com/gpu: 1
  nodeSelector: 
    nvidia.com/gpu.product: NVIDIA-A10G 